name: test upload and download artifact
on: [push]
jobs:
    test-upload-download-artifact:
        runs-on: ubuntu-latest
        env:
          file_name: artifact
        steps:
            - uses: actions/checkout@v3
            - uses: actions/upload-artifact@v3
              with:
                name: ${{env.file_name}}
                path: ./${{env.file_name}}.txt
            - uses: actions/download-artifact
              with:
                name: ${{env.file_name}}
                path: ./downloaded_${{env.file_name}}.txt
            - name: read downloaded file
              run: cat ./downloaded_${{env.file_name}}.txt