name: cicd
on: [push]
jobs:
    unit_test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: python hello.py
    build_and_upload_artifact:
        needs: unit_test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/upload-artifact@v3
              with:
                name: my-artifact
                path: .